name: Genera Indice per Kodi
on: [push]

# Forza l'uso del motore aggiornato richiesto da GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Crea index.html automatico
      run: |
        echo "<!DOCTYPE html><html><body><h1>I miei fighi lettori</h1><ul>" > index.html
        for file in *.zip; do
          if [ -f "$file" ]; then
            echo "<li><a href=\"$file\">$file</a></li>" >> index.html
          fi
        done
        echo "</ul></body></html>" >> index.html
    - name: Salva e pubblica
      run: |
        git config --global user.name "KodiBot"
        git config --global user.email "kodibot@github.com"
        git add index.html
        git diff-index --quiet HEAD || git commit -m "Lista aggiornata dal robot" -a
        git push
